### ISSUE TITLE
feature request : geocoding

### ISSUE THREAD

**Issue by zinkh** [saltcorn/leaflet-map#1]
Hi, great plugin for saltcorn, any plans to get geocoding inside the leaflet map so we can show points on maps from real addresses ?

**Comment by glutamate** [comment]
yes, definitely. Calculated fields is next up on the roadmap after I finish pop-up modals (will probably finish that today).

@zinkh can you tell me what the input would be, for instance I know how to do this from UK postcodes but what other input data do you have in mind? If we input addresses, then from which country? 

I'm not aware of any universal /global solution to geocoding input other than what 3 words, which is not so widely used

**Comment by zinkh** [comment]
Actually there is some plugins of leaflet that let you find any location in the world by typing an adress, here is the link link : [https://leafletjs.com/plugins.html#geocoding](url) most of hem are Open Source, but some use private limited API. I am no programmer so i can't tell which one is easier to implement.
There is also some API that allows to convert coordinates to addresses : [https://opencagedata.com/tutorials/geocode-in-leaflet](url)
What3words are using a conversion tool on their website to find location from address, but i can't find a description of this feature in the api demos.
For me this can have 2 uses, the address is stored as a string in the table and converted to mapview in the "show" view template, otherwise the user select a location from a map in the "view" template, then it is converted as a string in the tables, hope this is clear enough... :(

**Comment by glutamate** [comment]
Thanks, this is super helpful in terms of designing the calculated fields system. The bare basics are now in place, next I will look at being able to define functions in plugins and this will be a use case

**Comment by glutamate** [comment]
geocoding plugin here: https://github.com/saltcorn/nominatim-geocode

**Comment by zinkh** [comment]
Awesome,
Thank you so much. I'll try it right away.

**Comment by zinkh** [comment]
I must be doing something wrong, i can't get it to work :
- setting long and lat manually works
- creating a lat and long calculated fields with this expression "geocode_lat({city: adresse_ville})"throws this error : [object Promise] in showview, and the map not working.
- creating field named geocode_lat and geocode_long is not working, throwing error function geocode_long not defined.
![image](https://user-images.githubusercontent.com/1330905/95914719-6c70dc00-0da6-11eb-8e8b-0fd293ae75fb.png)

**Comment by glutamate** [comment]
@zinkh Did you make this a stored calculated field? Geocode lookups are asynchronous functions and therefore must be used in stored fields.

I could probably try to detect that and signal an appropriate error

**Comment by zinkh** [comment]
My bad i didn't see i had to check the stored label under calculated when creating the table field.
Thank you so much, maybe next request would be querying multiple adresses in one map.
