### ISSUE TITLE
Bug: css file not loaded by browser because the mime type is html

### ISSUE THREAD

**Issue by kevin8181** [saltcorn/leaflet-map#6]
see title, would fix myself but I'm not sure how from looking at the code

![image](https://user-images.githubusercontent.com/66894759/133368374-bfde9887-c4ec-4c3f-95a8-f20f3ea2c4f5.png)

@glutamate

**Comment by glutamate** [comment]
i think this is one of the bugs that were recently fixed, try new versions of saltcorn and this plugin
